#!/bin/bash -eux
# https://flight-manual.atom.io/getting-started/sections/installing-atom/#platform-linux
# https://github.com/atom/atom/releases/latest

curl -L https://packagecloud.io/AtomEditor/atom/gpgkey | sudo apt-key add -
sudo sh -c 'echo "deb [arch=amd64] https://packagecloud.io/AtomEditor/atom/any/ any main" > /etc/apt/sources.list.d/atom.list'
sudo apt-get -y update
# Install Atom
sudo apt-get -y install atom
# Install Atom Beta
# sudo apt-get install atom-beta

# sudo add-apt-repository -y ppa:webupd8team/atom

# sudo apt -y update
# sudo apt -y install atom

# configure atom with nice packages for RN development
apm install atom-beautify
apm install nuclide
apm install split-lines
apm install tool-bar
apm install language-babel
apm install language-ocaml
apm install highlight-selected
apm install linter-eslint

# Setup nuclide dependencies
echo "################################"
echo "## Please open Atom, then select"
echo "## Edit -> Preferences"
echo "## Under Packages, find Nuclide"
echo "## Click Settings under Nuclide"
echo "## Click 'Install Recommended Packages on Startup'"
echo "## Quit Atom, re-open it"
echo "################################"

