#!/bin/bash -eux
# https://flight-manual.atom.io/getting-started/sections/installing-atom/#platform-linux
# https://github.com/atom/atom/releases/latest

curl -L https://packagecloud.io/AtomEditor/atom/gpgkey | sudo apt-key add -
sudo sh -c 'echo "deb [arch=amd64] https://packagecloud.io/AtomEditor/atom/any/ any main" > /etc/apt/sources.list.d/atom.list'
sudo apt-get update
# Install Atom
sudo apt-get install atom
# Install Atom Beta
# sudo apt-get install atom-beta

# sudo add-apt-repository -y ppa:webupd8team/atom

# sudo apt -y update
# sudo apt -y install atom


