#!/bin/bash

sudo apt-get -y install software-properties-common
sudo add-apt-repository -y ppa:deadsnakes/ppa

sudo apt-get -y update
sudo apt-get -y install \
  python3 \
  python3.6 \
  python3-venv \
  python3-pip \
  python-pip \
  virtualenv


