#!/bin/bash -eux

wget -qO - https://download.sublimetext.com/sublimehq-pub.gpg | \
  sudo apt-key add -

echo "deb https://download.sublimetext.com/ apt/stable/" | \
sudo tee /etc/apt/sources.list.d/sublime-text.list

sudo apt-get -y update

sudo apt-get -y install sublime-text

# sudo apt-get remove sublime-text && sudo apt-get autoremove

# sudo add-apt-repository -y ppa:webupd8team/sublime-text-3
# sudo apt-get -y update
# sudo apt-get -y install sublime-text-installer


