#!/bin/bash -eux

## Add yarn repo
curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -
echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list

sudo apt-get -y update
sudo apt-get -y install npm yarn

function npm_cafile {
  for cafile in $@
  do
    if -f $cafile
    then
      npm config set cafile $cafile
      npm config set "strict-ssl" true
    fi
  done
}

npm_cafile $( ruby -ropenssl -e 'puts OpenSSL::X509::DEFAULT_CERT_FILE' )
npm_cafile /etc/ssl/certs/ca-certificates.crt

sudo npm install -g n

sudo n latest

