#!/bin/sh -eux

## Add yarn repo
curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -
echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list

sudo apt-get -y update
sudo apt-get -y install npm yarn

if [[ $(uname) -eq 'Darwin' ]]
then
  # this command will direct npm to use the ca cert pem bundle homebrew created when 
  # it installed openssl
  cafile=$( ruby -ropenssl -e 'puts OpenSSL::X509::DEFAULT_CERT_FILE' )
  if -f $cafile
  then
    npm config set cafile $cafile
    npm config set "strict-ssl" true
  fi
else
  cafile=/etc/ssl/certs/ca-certificates.crt
  if -f $cafile
  then
    npm config set cafile $cafile
    npm config set "strict-ssl" true
  fi
fi

sudo npm install -g n

sudo n latest

